### ISSUE TITLE
No GL Display on Linux

### ISSUE THREAD

**Issue by gameblabla** [3dfxdev/hyper3DGE#57] opened 2018-01-25 00:09 UTC
Currently, when attempting to run 3DGE on linux, all you get is a black display.
Last commit before that to work with few modifications was the git commit from December 7.
When raa-eruanna attempted to fix Linux support after some windows code was added in src/system/i_video.cc, he actually broke the display on Linux.
(https://github.com/3dfxdev/hyper3DGE/commit/c90b785f2b77c3756a2117cb96b37efb1eaea547)

Fix is fairly trivial, its only a few lines of code.
I'll post a PR very shortly here.

**Comment by raa-eruanna** [comment] 2018-01-25 01:05
First of all, I am "she" and prefer to be referred as that way, and secondly, I have *NO* idea what was going on with that code, it was among a whole bunch of code that Coraline committed one night. Thirdly, the PR breaks Windows compile, so I will have to take a look at it more closely and figure out what's going on. It's possible to compile two completely separate code paths based on operating system and we may end up having to do that in order to fix this issue.

**Comment by gameblabla** [comment] 2018-01-25 01:13
Yeah that's why i said this needed some testing on Windows. i was not sure if this would work on Windows. However, as it is now, it still prevents the Linux build from working properly.
Feel to free to provide your own fixes.

**Comment by raa-eruanna** [comment] 2018-01-25 01:21
Yeah I am just going to rewrite that entire thing using the code that was there previously before all those commits.

**Comment by Corbachu** [comment] 2018-01-25 23:45
Reopened as reported by @dsdman

**Comment by gameblabla** [comment] 2018-01-26 04:45
To me, it does not look like a driver issue at all. It's really due to the fact there's some Windows-specific code and the way its written means that it will break on Linux and vice-versa if reversed. Hence why she was suggesting rewriting the code. I'm surprised dsdman could not get it to work. He must have had applied the patches wrong.

**Comment by gameblabla** [comment] 2018-01-26 05:35
As of latest commit, this issue is fixed. At least it is for me with nouveau and llvmpipe.

**Comment by raa-eruanna** [comment] 2018-01-26 05:38
It works fine for me too, when using VirtualBox and "-norenderbuffers" - but I can't test it on my bare metal Linux system because that one's running a few Discord bots and it's crashed the kernel on that one before.

**Comment by gameblabla** [comment] 2018-01-26 05:45
For me, it also works with render buffers too and i'm using bare metal. I just need to try it with the Nvidia proprietary drivers.

**Comment by gameblabla** [comment] 2018-01-26 17:01
As i reported here (https://github.com/3dfxdev/hyper3DGE/issues/47), using the Nvidia proprietary drivers also work fine too. I'm using Devuan unstable as my linux distribution.

**Comment by dsdman** [comment] 2018-01-26 18:20
@gameblabla What is the version number of the Nvidia proprietary drivers are you using? I'm thinking this issue may be due to my laptop's switchable graphics using Nvidia Optimus (very likely), or a new driver making some OpenGL calls deprecated (unlikely). I have set up my X11 server as discribed [here](https://wiki.archlinux.org/index.php/NVIDIA_Optimus#Using_nvidia) on the Arch Linux wiki. I am unable to replicate this setup using Nouveau, as it just segfaults when I try to start Xorg with it. 

Either way, it is a linux specific issue (at least on my machine), as the windows build works just fine in wine/native windows.

**Comment by gameblabla** [comment] 2018-01-26 18:26
@dsdman I was using 384.111 for the proprietary drivers. I heard that later versions had some issues with games on Linux and Nvidia was not recommending them. (that and the increased memory usage too) 
What is your GPU ? If its a Geforce 900 or later, then they won't work properly on nouveau.

**Comment by dsdman** [comment] 2018-01-26 18:38
@gameblabla I am using a Geforce GTX 960m (Maxwell architecture circa 2014-2015). From what I gather from Nvidia's website, this card seems to be the mobile equivalent of the desktop Geforce 750 TI (also Maxwell), just clocked slightly higher. Until I can get nouveau working somehow, I am stuck using nvidia 387.34. I guess I'll continue to use the windows version until I can figure out the cause of this problem.

**Comment by dsdman** [comment] 2018-01-26 18:47
Okay, so I did more testing, and I finally got 3DGE to work in Linux (proprietary driver). As it turns out, it works fine if you use a compositing window manager or a compositor, but it doesn't give a display if you don't use a compositor (ie Openbox, i3, dwm). This issue can be closed.

**Comment by gameblabla** [comment] 2018-01-26 18:54
Oh i get it now. This is actually not a EDGE issue but an Optimus/Prime one. If you have two graphics card, you may not get a GL display unless you use a compositor. That also explains why it worked on my desktop with an Nvidia but not on yours since you're on Optimus.

It actually documented here
https://wiki.archlinux.org/index.php/PRIME

> ### When an application is rendered with the discrete card, it only renders a black screen
> In some cases PRIME needs a composition manager to properly work. 
> If your window manager >doesn’t do compositing, you can use xcompmgr on top of it.
> If you use Xfce, 
> you can go to Menu->Settings->Window Manager Tweaks->Compositor and enable > compositing,
> then try again your application.

**Comment by Corbachu** [comment] 2018-01-27 01:20
We also have a setting that gets enabled for Optimus GPU:

r_gpuswitch, which is found in e_main in _DoSystemStartup()_. I've never had a need for it so I didn't look into it too much, but nevertheless it is there.

So it appears the engine is back in a stable state for both Linux and Windows. I'll go ahead and close the issue =)

**Closed by Corbachu** 2018-01-27 01:20 UTC
